services: mongodb
language: ruby
matrix:
  include:
    - rvm: 2.4.0
      env:
        - MONGOID_VERSION=6
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=6
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=5
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=4
    - rvm: 2.3.1
      env:
        - MONGOID_VERSION=3
    - rvm: 2.3.0
  allow_failures:
    - rvm: 2.4.0
    - rvm: ruby-head
    - rvm: jruby-head
before_install:
  - gem update --system
  - gem update bundler
gemfile:
  - Gemfile